#application.properties
spring.application.name=lumibooks-backend

# Configuración del puerto del servidor
server.port=8081

# Activar el perfil de desarrollo para usar las propiedades específicas de desarrollo
spring.profiles.active=dev
