# application.properties

# Configuración base de la aplicación.
# Contiene propiedades comunes para todos los perfiles.
#
# Las configuraciones específicas de cada entorno se encuentran en:
# - application-dev.properties (desarrollo)
# - application-prod.properties (producción)

spring.application.name=lumibooks-backend

# Puerto donde se ejecuta la aplicación.
server.port=8081