# application-dev.properties

# BASE DE DATOS (usando variables del sistema)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA (tú controlas la BD manualmente)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# REDIS
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:2592000000}

# COOKIES
cookie.secure=${COOKIE_SECURE:false}

# CORS (dominio del frontend en dev)
app.cors.allowed-origins=http://localhost:3000

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}