# application-dev.properties

# BASE DE DATOS (usando variables del sistema)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA (tú controlas la BD manualmente)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true